# Makefile.dtc
#
# This is not a complete Makefile of itself.  Instead, it is designed to
# be easily embeddable into other systems of Makefiles.
#
DTC_SRCS = \
	checks.c \
	data.c \
	dtc.c \
	flattree.c \
	fstree.c \
	ir.c \
	ir_builtin.c \
	ir_dump.c \
	ir_emit.c \
	ir_eval.c \
	ir_scope.c \
	livetree.c \
	nv.c \
	srcpos.c \
	treesource.c \
	util.c

DTC_GEN_SRCS = dtc-lexer.lex.c dtc-parser.tab.c
DTC_OBJS = $(DTC_SRCS:%.c=%.o) $(DTC_GEN_SRCS:%.c=%.o)
